name: Deploy on server
on: [push]

jobs:
  build_and_push_docker_image:
    name: Build and Push to Yandex CR 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        if: ${{ (github.ref == 'refs/heads/main') }}
      - name: Yandex CR Login
        uses: yc-actions/yc-cr-login@v0.1-alpha
        if: ${{ (github.ref == 'refs/heads/main') }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEY }}
      - name: Build image
        if: ${{ (github.ref == 'refs/heads/main') }}
        env: 
          CR_REGISTRY: crpftbrsrru52q0qfefi
          CR_REPO: sense-and-home-client
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:latest .
      - name: Push image
        if: ${{ (github.ref == 'refs/heads/main') }}
        env: 
          CR_REGISTRY: crpftbrsrru52q0qfefi
          CR_REPO: sense-and-home-client
        run: |
          docker push cr.yandex/$CR_REGISTRY/$CR_REPO:latest

  deploy:
    name: Deploy on server
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: SSH connect and deploy
        uses: appleboy/ssh-action@master
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: CR_REGISTRY,CR_REPO
          script: |
            cd frontend 
            docker pull cr.yandex/$CR_REGISTRY/$CR_REPO:latest
            docker compose up --no-deps -d client
